import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// 1. Workbox Standard Configuration
self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Share Target Handler
self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);
    if (event.request.method === 'POST' && url.pathname === '/share-target') {
        event.respondWith(
            (async () => {
                const formData = await event.request.formData();
                const media = formData.get('media');
                const text = formData.get('text');
                const title = formData.get('title');
                const sharedUrl = formData.get('url');

                const cache = await caches.open('share-target-cache');

                if (media) {
                    await cache.put('/api/share-media', new Response(media));
                }

                // Combine text parts
                const fullText = [title, text, sharedUrl].filter(Boolean).join('\n');

                const metadata = {
                    text: fullText,
                    hasMedia: !!media,
                    timestamp: Date.now()
                };

                await cache.put('/api/share-data', new Response(JSON.stringify(metadata)));

                return Response.redirect('/share?processing=true', 303);
            })()
        );
    }
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// 2. Firebase Messaging Service Worker
// Import scripts from CDN as Firebase JS SDK isn't fully tree-shakable/bundled easily in SW without issues sometimes.
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-messaging-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-firestore-compat.js');

// Initialize the Firebase app in the service worker
if (firebase.apps.length === 0) {
    firebase.initializeApp({
        apiKey: "AIzaSyAtqHwOk2zwqdmr_3puMCVH_aAmzx0GtTI",
        authDomain: "whatsappclone-50b5b.firebaseapp.com",
        projectId: "whatsappclone-50b5b",
        storageBucket: "whatsappclone-50b5b.firebasestorage.app",
        messagingSenderId: "662334343258",
        appId: "1:662334343258:web:a1b7a9fe49563c9aeaf063",
        databaseURL: "https://whatsappclone-50b5b-default-rtdb.firebaseio.com"
    });
}

// Retrieve an instance of Firebase Messaging
const messaging = firebase.messaging();

// Initialize Firestore (Compat)
const db = firebase.firestore();

messaging.onBackgroundMessage(async (payload) => {
    console.log('[firebase-messaging-sw.js] 🔔 Received background message ', payload);

    // BACKGROUND DELIVERY LOGIC (Double Ticks)
    try {
        const { chatId, senderId } = payload.data || {};

        if (chatId && senderId) {
            console.log(`[SW] Attempting to mark messages in chat ${chatId} from ${senderId} as delivered...`);

            // Query for undelivered messages from this specific sender
            const messagesRef = db.collection('chats').doc(chatId).collection('messages');
            const q = messagesRef
                .where('delivered', '==', false)
                .where('senderId', '==', senderId); // Only mark incoming messages from the notifier

            const snapshot = await q.get();

            if (!snapshot.empty) {
                const batch = db.batch();
                let count = 0;

                snapshot.forEach(doc => {
                    batch.update(doc.ref, { delivered: true });
                    count++;
                });

                if (count > 0) {
                    await batch.commit();
                    console.log(`[SW] Successfully marked ${count} messages as delivered.`);
                }
            }
        }
    } catch (error) {
        console.error('[SW] Error updating delivery status:', error);
    }

    // Customize notification here
    const notificationTitle = payload.notification.title;
    const notificationOptions = {
        body: payload.notification.body,
        icon: '/nova-icon.png', // Updated to use the new PNG icon
        badge: '/nova-icon.png',
        tag: payload.notification.tag || 'general',
        data: payload.data || {}
    };

    return self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle Notification Click
self.addEventListener('notificationclick', function (event) {
    console.log('[firebase-messaging-sw.js] Notification click received.');
    event.notification.close();

    // Open the app or focus the window
    event.waitUntil(
        clients.matchAll({
            type: "window",
            includeUncontrolled: true
        }).then(function (clientList) {
            // Check if there's already a window open
            for (var i = 0; i < clientList.length; i++) {
                var client = clientList[i];
                // Focus if already open
                if (client.url.indexOf('/') !== -1 && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise open a new window
            if (clients.openWindow) {
                return clients.openWindow('/');
            }
        })
    );
});
