importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.4.1/workbox-sw.js');

// 1. Workbox Standard Configuration
self.skipWaiting();
workbox.core.clientsClaim();
workbox.precaching.cleanupOutdatedCaches();

// Share Target Handler
self.addEventListener('fetch', (event) => {
    const url = new URL(event.request.url);
    if (event.request.method === 'POST' && url.pathname === '/share-target') {
        event.respondWith(
            (async () => {
                const formData = await event.request.formData();
                const media = formData.get('media');
                const text = formData.get('text');
                const title = formData.get('title');
                const sharedUrl = formData.get('url');

                const cache = await caches.open('share-target-cache');

                if (media) {
                    await cache.put('/api/share-media', new Response(media));
                }

                // Combine text parts
                const fullText = [title, text, sharedUrl].filter(Boolean).join('\n');

                const metadata = {
                    text: fullText,
                    hasMedia: !!media,
                    timestamp: Date.now()
                };

                await cache.put('/api/share-data', new Response(JSON.stringify(metadata)));

                return Response.redirect('/share?processing=true', 303);
            })()
        );
    }
});

// Precache all assets generated by Vite
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);

// 2. Navigation Fallback (Fix for 404 on refresh)
// Use a more robust check to ensure index.html exists in precache
const navigationHandler = async (params) => {
    try {
        const cacheKey = workbox.precaching.getCacheKeyForURL('index.html');
        if (cacheKey) {
            const cachedResponse = await caches.match(cacheKey);
            if (cachedResponse) return cachedResponse;
        }
    } catch (e) {
        console.error('Error in SW navigation handler:', e);
    }
    // Fallback to network
    return fetch(params.request);
};

workbox.routing.registerRoute(
    new workbox.routing.NavigationRoute(navigationHandler)
);

// 3. Firebase Messaging Service Worker
// Import scripts from CDN as Firebase JS SDK isn't fully tree-shakable/bundled easily in SW without issues sometimes.
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-messaging-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-firestore-compat.js');

// Initialize the Firebase app in the service worker
const firebaseConfig = {
    apiKey: "__VITE_FIREBASE_API_KEY__",
    authDomain: "__VITE_FIREBASE_AUTH_DOMAIN__",
    projectId: "__VITE_FIREBASE_PROJECT_ID__",
    storageBucket: "__VITE_FIREBASE_STORAGE_BUCKET__",
    messagingSenderId: "__VITE_FIREBASE_MESSAGING_SENDER_ID__",
    appId: "__VITE_FIREBASE_APP_ID__",
    databaseURL: "__VITE_FIREBASE_DATABASE_URL__"
};

// If placeholders haven't been replaced (e.g. dev mode or build issue), 
// we try to use global replacements if provided via vite-plugin-pwa.
if (firebaseConfig.apiKey.startsWith('__')) {
    console.warn("Service Worker using build-time placeholders. Ensure injection is working.");
}

if (firebase.apps.length === 0) {
    firebase.initializeApp(firebaseConfig);
}

// Retrieve an instance of Firebase Messaging
const messaging = firebase.messaging();

// Initialize Firestore (Compat)
const db = firebase.firestore();

messaging.onBackgroundMessage(async (payload) => {
    console.log('[firebase-messaging-sw.js] 🔔 Received background message ', payload);

    // BACKGROUND DELIVERY LOGIC (Double Ticks)
    // BACKGROUND DELIVERY LOGIC - REMOVED due to permission issues in SW
    // The client will mark messages as delivered when it connects/focuses.


    // Customize notification here
    const notificationTitle = payload.notification.title;
    const notificationOptions = {
        body: payload.notification.body,
        icon: '/nova-icon.png', // Updated to use the new PNG icon
        badge: '/nova-icon.png',
        tag: payload.notification.tag || 'general',
        data: payload.data || {}
    };

    return self.registration.showNotification(notificationTitle, notificationOptions);
});

// Handle Notification Click
self.addEventListener('notificationclick', function (event) {
    console.log('[firebase-messaging-sw.js] Notification click received.');
    event.notification.close();

    // Open the app or focus the window
    event.waitUntil(
        clients.matchAll({
            type: "window",
            includeUncontrolled: true
        }).then(function (clientList) {
            // Check if there's already a window open
            for (var i = 0; i < clientList.length; i++) {
                var client = clientList[i];
                // Focus if already open
                if (client.url.indexOf('/') !== -1 && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise open a new window
            if (clients.openWindow) {
                return clients.openWindow('/');
            }
        })
    );
});
